version: '3.8'

services:
  # บริการ MySQL
  mysql_db:
    image: mysql:8.0
    container_name: cinema_mysql
    restart: always
    environment:
      MYSQL_DATABASE: cinema_db
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD} # ดึงค่าจากไฟล์ .env
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  # บริการ MongoDB
  mongo_db:
    image: mongo:latest
    container_name: cinema_mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  # บริการ Backend (Node.js)
  backend:
    build: ./backend
    container_name: cinema_backend
    ports:
      - "5000:5000"
    depends_on:
      - mysql_db
      - mongo_db
    environment:
      DB_HOST: mysql_db
      MONGO_URI: mongodb://root:rootpassword@mongo_db:27017/cinema_logs?authSource=admin

volumes:
  mysql_data:
  mongo_data: